service: api-pdf2text

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.[t|j]s # Exclude test files
  prune:
    automatic: true
    number: 5 # Number of versions to keep
  apigwBinary:
    types: #list of mime-types
      - 'application/pdf'
      - 'multipart/form-data'

functions:
  uploadPdf:
    handler: src/uploadPdf.default
    events:
      - http:
          path: uploadPdf
          method: post
          cors: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin
